// Builds a self-contained interactive ER-diagram HTML page from parsed schema data.
// Draggable tables, zoom/pan, and curved foreign-key relationship lines.

export function buildHtml(data, title) {
  const json = JSON.stringify(data);
  const safeTitle = (title || "Database Schema").replace(/</g, "&lt;");

  // Use replacement functions so "$" sequences in the data/title are treated
  // literally, and replace ALL occurrences of the title placeholder.
  return PAGE.replaceAll("__TITLE__", () => safeTitle).replace(
    '"__SCHEMA_DATA__"',
    () => json
  );
}

const PAGE = [
  "<!DOCTYPE html>",
  '<html lang="en">',
  "<head>",
  '<meta charset="utf-8" />',
  '<meta name="viewport" content="width=device-width, initial-scale=1" />',
  "<title>__TITLE__</title>",
  "<style>",
  ":root{--bg:#0f172a;--grid:#1e293b;--card:#1e293b;--card-border:#334155;--header:#6366f1;--text:#e2e8f0;--muted:#94a3b8;--pk:#fbbf24;--fk:#38bdf8;--line:#64748b;}",
  "*{box-sizing:border-box;}",
  "html,body{margin:0;height:100%;overflow:hidden;font-family:ui-sans-serif,system-ui,Segoe UI,Roboto,Helvetica,Arial,sans-serif;background:var(--bg);color:var(--text);}",
  "#viewport{position:absolute;inset:0;cursor:grab;background-image:radial-gradient(var(--grid) 1px,transparent 1px);background-size:24px 24px;}",
  "#viewport.panning{cursor:grabbing;}",
  "#world{position:absolute;left:0;top:0;transform-origin:0 0;}",
  "svg#edges{position:absolute;left:0;top:0;overflow:visible;pointer-events:none;}",
  ".table{position:absolute;width:250px;background:var(--card);border:1px solid var(--card-border);border-radius:10px;box-shadow:0 8px 24px rgba(0,0,0,.35);user-select:none;font-size:13px;overflow:hidden;}",
  ".table .head{background:var(--header);color:#fff;font-weight:600;padding:8px 12px;cursor:grab;letter-spacing:.2px;}",
  ".table .head:active{cursor:grabbing;}",
  ".row{display:flex;justify-content:space-between;gap:10px;padding:6px 12px;border-top:1px solid var(--card-border);align-items:center;}",
  ".row .col{display:flex;align-items:center;gap:6px;}",
  ".row .type{color:var(--muted);font-size:11.5px;font-family:ui-monospace,Menlo,Consolas,monospace;}",
  ".badge{font-size:9px;font-weight:700;padding:1px 5px;border-radius:5px;letter-spacing:.5px;}",
  ".badge.pk{background:rgba(251,191,36,.18);color:var(--pk);}",
  ".badge.fk{background:rgba(56,189,248,.18);color:var(--fk);}",
  ".badge.uq{background:rgba(148,163,184,.18);color:var(--muted);}",
  ".name.pk{color:var(--pk);}",
  "path.edge{fill:none;stroke:var(--line);stroke-width:1.6;}",
  "circle.endpoint{fill:var(--fk);}",
  "#toolbar{position:absolute;top:12px;left:12px;z-index:10;display:flex;gap:8px;align-items:center;background:rgba(30,41,59,.9);border:1px solid var(--card-border);border-radius:8px;padding:6px 10px;font-size:12px;}",
  "#toolbar button{background:#334155;color:var(--text);border:none;border-radius:6px;padding:4px 9px;cursor:pointer;font-size:12px;}",
  "#toolbar button:hover{background:#475569;}",
  "#toolbar .label{color:var(--muted);}",
  "</style>",
  "</head>",
  "<body>",
  '<div id="toolbar">',
  '<span class="label">__TITLE__</span>',
  '<button id="fit">Fit</button>',
  '<button id="reset">Reset zoom</button>',
  '<span class="label" id="zoomlabel">100%</span>',
  "</div>",
  '<div id="viewport">',
  '<div id="world">',
  '<svg id="edges"></svg>',
  "</div>",
  "</div>",
  "<script>",
  "var DATA = \"__SCHEMA_DATA__\";",
  "(function(){",
  "  var viewport=document.getElementById('viewport');",
  "  var world=document.getElementById('world');",
  "  var svg=document.getElementById('edges');",
  "  var zoomLabel=document.getElementById('zoomlabel');",
  "  var tables=DATA.tables||[];",
  "  var refs=DATA.refs||[];",
  "  var els={};   // name -> table element",
  "  var pos={};   // name -> {x,y}",
  "  var pan={x:60,y:80}, zoom=1;",
  "",
  "  function applyTransform(){",
  "    world.style.transform='translate('+pan.x+'px,'+pan.y+'px) scale('+zoom+')';",
  "    zoomLabel.textContent=Math.round(zoom*100)+'%';",
  "  }",
  "",
  "  // Build table cards in a simple grid.",
  "  var perRow=Math.max(1,Math.ceil(Math.sqrt(tables.length)));",
  "  var colW=300, rowH=260;",
  "  tables.forEach(function(t,idx){",
  "    var el=document.createElement('div');",
  "    el.className='table';",
  "    var head=document.createElement('div');",
  "    head.className='head';",
  "    head.textContent=t.name;",
  "    el.appendChild(head);",
  "    t.columns.forEach(function(c){",
  "      var row=document.createElement('div');",
  "      row.className='row';",
  "      row.setAttribute('data-col',c.name);",
  "      var left=document.createElement('div');",
  "      left.className='col';",
  "      var nm=document.createElement('span');",
  "      nm.className='name'+(c.isPk?' pk':'');",
  "      nm.textContent=c.name;",
  "      left.appendChild(nm);",
  "      if(c.isPk){left.appendChild(badge('pk','PK'));}",
  "      if(c.isFk){left.appendChild(badge('fk','FK'));}",
  "      if(c.isUnique&&!c.isPk){left.appendChild(badge('uq','UQ'));}",
  "      var ty=document.createElement('span');",
  "      ty.className='type';",
  "      ty.textContent=c.type;",
  "      row.appendChild(left);",
  "      row.appendChild(ty);",
  "      el.appendChild(row);",
  "    });",
  "    world.appendChild(el);",
  "    els[t.name]=el;",
  "    var x=60+(idx%perRow)*colW;",
  "    var y=40+Math.floor(idx/perRow)*rowH;",
  "    pos[t.name]={x:x,y:y};",
  "    el.style.left=x+'px';",
  "    el.style.top=y+'px';",
  "    head.addEventListener('mousedown',startDrag(t.name));",
  "  });",
  "",
  "  function badge(kind,txt){",
  "    var b=document.createElement('span');",
  "    b.className='badge '+kind;",
  "    b.textContent=txt;",
  "    return b;",
  "  }",
  "",
  "  // ----- Edges -----",
  "  var edgeEls=[];",
  "  refs.forEach(function(){",
  "    var p=document.createElementNS('http://www.w3.org/2000/svg','path');",
  "    p.setAttribute('class','edge');",
  "    svg.appendChild(p);",
  "    var c1=document.createElementNS('http://www.w3.org/2000/svg','circle');",
  "    c1.setAttribute('class','endpoint');c1.setAttribute('r','3');",
  "    var c2=document.createElementNS('http://www.w3.org/2000/svg','circle');",
  "    c2.setAttribute('class','endpoint');c2.setAttribute('r','3');",
  "    svg.appendChild(c1);svg.appendChild(c2);",
  "    edgeEls.push({path:p,a:c1,b:c2});",
  "  });",
  "",
  "  function rowCenterY(name,col){",
  "    var el=els[name];",
  "    var row=el.querySelector('[data-col=\"'+col+'\"]');",
  "    var top=row?row.offsetTop+row.offsetHeight/2:el.offsetHeight/2;",
  "    return pos[name].y+top;",
  "  }",
  "",
  "  function updateEdges(){",
  "    refs.forEach(function(r,i){",
  "      var sEl=els[r.fromTable], tEl=els[r.toTable];",
  "      if(!sEl||!tEl)return;",
  "      var sMid=pos[r.fromTable].x+sEl.offsetWidth/2;",
  "      var tMid=pos[r.toTable].x+tEl.offsetWidth/2;",
  "      var sRight=tMid>=sMid;",
  "      var x1=pos[r.fromTable].x+(sRight?sEl.offsetWidth:0);",
  "      var x2=pos[r.toTable].x+(sRight?0:tEl.offsetWidth);",
  "      var y1=rowCenterY(r.fromTable,r.fromColumn);",
  "      var y2=rowCenterY(r.toTable,r.toColumn);",
  "      var dx=Math.max(40,Math.abs(x2-x1)/2);",
  "      var c1x=x1+(sRight?dx:-dx);",
  "      var c2x=x2+(sRight?-dx:dx);",
  "      var d='M '+x1+' '+y1+' C '+c1x+' '+y1+', '+c2x+' '+y2+', '+x2+' '+y2;",
  "      var e=edgeEls[i];",
  "      e.path.setAttribute('d',d);",
  "      e.a.setAttribute('cx',x1);e.a.setAttribute('cy',y1);",
  "      e.b.setAttribute('cx',x2);e.b.setAttribute('cy',y2);",
  "    });",
  "  }",
  "",
  "  // ----- Table dragging -----",
  "  var drag=null;",
  "  function startDrag(name){",
  "    return function(ev){",
  "      ev.preventDefault();ev.stopPropagation();",
  "      drag={name:name,sx:ev.clientX,sy:ev.clientY,ox:pos[name].x,oy:pos[name].y};",
  "    };",
  "  }",
  "",
  "  // ----- Panning -----",
  "  var panning=null;",
  "  viewport.addEventListener('mousedown',function(ev){",
  "    if(drag)return;",
  "    panning={sx:ev.clientX,sy:ev.clientY,ox:pan.x,oy:pan.y};",
  "    viewport.classList.add('panning');",
  "  });",
  "  document.addEventListener('mousemove',function(ev){",
  "    if(drag){",
  "      var nx=drag.ox+(ev.clientX-drag.sx)/zoom;",
  "      var ny=drag.oy+(ev.clientY-drag.sy)/zoom;",
  "      pos[drag.name]={x:nx,y:ny};",
  "      els[drag.name].style.left=nx+'px';",
  "      els[drag.name].style.top=ny+'px';",
  "      updateEdges();",
  "    }else if(panning){",
  "      pan.x=panning.ox+(ev.clientX-panning.sx);",
  "      pan.y=panning.oy+(ev.clientY-panning.sy);",
  "      applyTransform();",
  "    }",
  "  });",
  "  document.addEventListener('mouseup',function(){",
  "    drag=null;panning=null;viewport.classList.remove('panning');",
  "  });",
  "",
  "  // ----- Zoom -----",
  "  viewport.addEventListener('wheel',function(ev){",
  "    ev.preventDefault();",
  "    var rect=viewport.getBoundingClientRect();",
  "    var mx=ev.clientX-rect.left, my=ev.clientY-rect.top;",
  "    var wx=(mx-pan.x)/zoom, wy=(my-pan.y)/zoom;",
  "    var factor=ev.deltaY<0?1.1:1/1.1;",
  "    zoom=Math.min(2.5,Math.max(0.2,zoom*factor));",
  "    pan.x=mx-wx*zoom; pan.y=my-wy*zoom;",
  "    applyTransform();",
  "  },{passive:false});",
  "",
  "  document.getElementById('reset').addEventListener('click',function(){",
  "    zoom=1;pan={x:60,y:80};applyTransform();",
  "  });",
  "  document.getElementById('fit').addEventListener('click',fit);",
  "",
  "  function fit(){",
  "    var minX=1e9,minY=1e9,maxX=-1e9,maxY=-1e9;",
  "    tables.forEach(function(t){",
  "      var el=els[t.name];var p=pos[t.name];",
  "      minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);",
  "      maxX=Math.max(maxX,p.x+el.offsetWidth);maxY=Math.max(maxY,p.y+el.offsetHeight);",
  "    });",
  "    var w=viewport.clientWidth, h=viewport.clientHeight;",
  "    var bw=maxX-minX+80, bh=maxY-minY+80;",
  "    zoom=Math.min(2,Math.max(0.2,Math.min(w/bw,h/bh)));",
  "    pan.x=(w-bw*zoom)/2-(minX-40)*zoom;",
  "    pan.y=(h-bh*zoom)/2-(minY-40)*zoom;",
  "    applyTransform();",
  "  }",
  "",
  "  applyTransform();",
  "  updateEdges();",
  "  setTimeout(fit,30);",
  "})();",
  "</script>",
  "</body>",
  "</html>",
].join("\n");
